# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_img',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
