# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20160226_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_link',
            field=models.SlugField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='post_tags',
            field=models.ManyToManyField(to='myblog.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
