# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 19:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_auto_20160226_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_publish_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
